CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE todo (
    "createdAt"     TIMESTAMP NOT NULL DEFAULT now(),
    "updatedAt"     TIMESTAMP,
    "deletedAt"     TIMESTAMP,
    "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "desc"          character varying(255),
    "name"          character varying(255),
    "check"         BOOLEAN NOT NULL DEFAULT FALSE
);